name: Next JS Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: "Deploy to Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}
          VERCEL_ORG_ID: ${{ secrets.ORGID }}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
          GMAIL_USERNAME: ${{secrets.GMAIL_USERNAME}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          NEXT_PUBLIC_GRAPHQL_DEV_URL: ${{secrets.NEXT_PUBLIC_GRAPHQL_DEV_URL}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}

          
